{"schema_version":"1.3.1","id":"GO-2021-0079","modified":"2024-05-20T16:03:47Z","published":"2021-04-14T20:04:52Z","aliases":["CVE-2018-18206","GHSA-vc3x-gx6c-g99f"],"summary":"Panic in github.com/bytom/bytom","details":"A malformed query can cause an out-of-bounds panic due to improper validation of arguments. If processing queries from untrusted parties, this may be used as a vector for denial of service attacks.","affected":[{"package":{"name":"github.com/bytom/bytom","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.0.4-0.20180831054840-1ac3c8ac4f2b"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/bytom/bytom/p2p/discover","symbols":["Network.checkTopicRegister"]}]}}],"references":[{"type":"FIX","url":"https://github.com/Bytom/bytom/pull/1307"},{"type":"FIX","url":"https://github.com/Bytom/bytom/commit/1ac3c8ac4f2b1e1df9675228290bda6b9586ba42"}],"credits":[{"name":"@yahtoo"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2021-0079","review_status":"REVIEWED"}}